version: '3.7'

services: 
  generator:
    build:
      context: .
      dockerfile: Dockerfile
    image: danlavrushko/fakerapi:1.1
    ports:
      - "8080:80"
  mail:
    image: mailhog/mailhog
    ports: 
      - "8025:8025"
      - "1025:1025"
